# Generated by Django 5.2.3 on 2026-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tags', models.CharField(blank=True, help_text='多个标签用英文逗号分隔', max_length=300)),
                ('categories', models.CharField(blank=True, help_text='多个分类用英文逗号分隔', max_length=300)),
                ('abbrlink', models.PositiveIntegerField(blank=True, null=True)),
                ('content_markdown', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章草稿',
                'verbose_name_plural': '文章草稿',
                'ordering': ['-updated_at'],
            },
        ),
    ]
